<?php

module_load_include('inc', 'uuid');

/**
 * Implements hook_comment_presave().
 */
function uuid_comment_comment_presave($comment) {
  // We generate the UUID here so it can be used by other hooks.
  if (is_null($comment->cid)) {
    $comment->uuid = uuid_uuid();
  }
}

/**
 * Implements hook_comment_insert().
 */
function uuid_comment_comment_insert($comment) {
  /*
    We save the UUID here because comments is "special" when it comes 
    to handling writes. eSPECIALy frustrating!
  */
  db_update('comment')
    ->fields(array('uuid' => $comment->uuid))
    ->condition('cid', $comment->cid)
    ->execute();
}
