<?php

module_load_include('inc', 'uuid');

/**
 * Add a UUID to a user role.
 *
 * @param
 *  $role the user role to add the UUID to.
 *
 * @return
 *   The number of rows affected - should always be 1.
 */
function uuid_role_add_uuid($role) {
  return db_update('role')
    ->fields(array('uuid' => uuid_uuid()))
    ->condition('rid', $role->rid)
    ->execute();
}

/**
 * Implements hook_user_role_insert().
 */
function uuid_role_user_role_insert($role) {
  return uuid_role_add_uuid($role);
}


/**
 * Implements hook_user_role_update().
 */
function uuid_role_user_role_update($role) {
  if (!isset($role->uuid)) {
    return uuid_role_add_uuid($role);
  }

  return TRUE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uuid_role_form_user_admin_role_alter(&$form, &$form_state, $form_id) {
  // Preserve the existing UUID if we have one
  if (isset($form_state['build_info']['args'][0]->uuid)) {
    $form['uuid'] = array(
      '#type' => 'value',
      '#value' => $form_state['build_info']['args'][0]->uuid,
    );
  }
}
